I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 319, in script
    play sound fall
  File "renpy/common/000statements.rpy", line 300, in execute_play_sound
    renpy.sound.play(_audio_eval(p["file"]),
  File "renpy/common/000statements.rpy", line 32, in _audio_eval
    return eval(expr, locals=store.audio.__dict__)
  File "game/script.rpy", line 319, in <module>
    play sound fall
NameError: name 'fall' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 319, in script
    play sound fall
  File "/Applications/renpy-7.4.11-sdk/renpy/ast.py", line 2015, in execute
    self.call("execute")
  File "/Applications/renpy-7.4.11-sdk/renpy/ast.py", line 2003, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "/Applications/renpy-7.4.11-sdk/renpy/statements.py", line 278, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 300, in execute_play_sound
    renpy.sound.play(_audio_eval(p["file"]),
  File "renpy/common/000statements.rpy", line 32, in _audio_eval
    return eval(expr, locals=store.audio.__dict__)
  File "/Applications/renpy-7.4.11-sdk/renpy/python.py", line 2276, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/Applications/renpy-7.4.11-sdk/renpy/python.py", line 2269, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 319, in <module>
    play sound fall
NameError: name 'fall' is not defined

Darwin-18.7.0-x86_64-i386-64bit
Ren'Py 7.4.11.2266
APEX and the Great Flame War 1.0
Sat Jan 22 12:27:01 2022
